name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create output directory
        run: mkdir -p .github/output
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/output/metrics.classic.svg
          user: Dalla936
          token: ${{ secrets.GITHUB_TOKEN }}
          # Base metrics
          base: header, activity, community, repositories, metadata
          # Popular plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_followup: yes
